### ISSUE TITLE
Fix coveralls.io badge automatic updation

### ISSUE THREAD

**Issue by sanjayaksaxena** [decisively/wink-utils#18]

**Comment by prtksxna** [comment]
Hmm, doesn't seem like there is anything wrong with the image that we're loading. A quick <kbd>⌘</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd> solved the issue though. Caching issue?

**Comment by sanjayaksaxena** [comment]
Working right now!

@rachnachakraborty and me had tried <kbd>⌘</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd> several times and it wasn't working... even on multiple browsers... 

Must be some kind of temporal malfunction!
