### ISSUE TITLE
Setup CLA process

### ISSUE THREAD

**Issue by prtksxna** [decisively/wink-utils#2]
Options (in the order I'd prefer): 
1. https://github.com/integrations/cla-assistant
2. https://www.clahub.com/

**Comment by sanjayaksaxena** [comment]
My choice was also option 1.

**Comment by prtksxna** [comment]
Setup CLA assistant for the entire organization. The CLA can be found here - https://gist.github.com/prtksxna/76a22ff03d2b58199b470c1acd06c983 - and was checked by @ambersinha07

**Comment by sanjayaksaxena** [comment]
Perfect 👍 +1
